version: '3.8'
services:
  client:
    build: .
    container_name: 'dungeons_and_dragons_frontend'
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules
      - ./:/app
    tty: true
